[package]
name = "conjure-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
http = "0.2.9"
percent-encoding = "2.2.0"
proc-macro2 = "1.0.47"
quote = "1.0.21"
structmeta = "0.2.0"
syn = { version = "2.0.15", features = ["full"] }
