[workspace.package]
version = "3.6.0"

[workspace]
resolver = "2"
members = [
    "conjure-codegen",
    "conjure-error",
    "conjure-http",
    "conjure-macros",
    "conjure-object",
    "conjure-rust",
    "conjure-serde",
    "conjure-test",
]

exclude = ["example-api"]
