[package]
name = "conjure-rust"
version = "3.2.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }

conjure-codegen = { version = "3.2.0", path = "../conjure-codegen" }
